# Generated by Django 5.2.4 on 2025-08-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VPNUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
                ),
                (
                    "vpn_username",
                    models.CharField(
                        max_length=100, verbose_name="VPN Имя пользователя"
                    ),
                ),
                (
                    "vpn_config",
                    models.CharField(max_length=100, verbose_name="Ключ к конфигу VPN"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активна"), ("expired", "Истекла")],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Дата истечения")),
                (
                    "traffic_used",
                    models.FloatField(verbose_name="Использовано трафика (ГБ)"),
                ),
                ("traffic_limit", models.FloatField(verbose_name="Лимит трафика (ГБ)")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "VPN Пользователь",
                "verbose_name_plural": "VPN Пользователи",
                "ordering": ["-expires_at"],
            },
        ),
    ]
