# Generated by Django 5.2.2 on 2025-08-29 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_vpnuser_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vpnuser",
            options={"verbose_name": "VPN User", "verbose_name_plural": "VPN Users"},
        ),
        migrations.RemoveField(
            model_name="vpnuser",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="vpnuser",
            name="status",
        ),
        migrations.RemoveField(
            model_name="vpnuser",
            name="traffic_limit",
        ),
        migrations.RemoveField(
            model_name="vpnuser",
            name="traffic_used",
        ),
        migrations.RemoveField(
            model_name="vpnuser",
            name="vpn_config",
        ),
        migrations.RemoveField(
            model_name="vpnuser",
            name="vpn_username",
        ),
        migrations.AddField(
            model_name="vpnuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="vpnuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AddField(
            model_name="vpnuser",
            name="username",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Telegram username"
            ),
        ),
        migrations.AlterField(
            model_name="vpnuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="vpnuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vpn_username",
                    models.CharField(max_length=100, verbose_name="VPN Username"),
                ),
                ("vpn_config", models.TextField(verbose_name="VPN Configuration")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "tariff",
                    models.CharField(
                        choices=[
                            ("1month", "1 Month - 178 RUB"),
                            ("3months", "3 Months - 450 RUB"),
                            ("6months", "6 Months - 690 RUB"),
                            ("12months", "12 Months - 840 RUB"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expiration Date")),
                (
                    "traffic_used",
                    models.FloatField(default=0, verbose_name="Traffic Used (GB)"),
                ),
                (
                    "traffic_limit",
                    models.FloatField(default=100, verbose_name="Traffic Limit (GB)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="main.vpnuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-expires_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="RUB", max_length=3)),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payload", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="main.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
    ]
